export default {
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    SCHEMA_ERROR: 'SCHEMA_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_EXPI: 'TOKEN_EXPI',
}