export default {
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    SCHEMA_ERROR: 'SCHEMA_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_EXPI: 'TOKEN_EXPI',
    INVALID_CLIENT: 'INVALID_CLIENT',
    INVALID_REDIRECT: 'INVALID_REDIRECT',
    APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
}